version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    ports:
     - "3000:3000"
    depends_on:
     - db
  db:
    image: mongo
    container_name: db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"